# -*- coding: utf-8 -*-
"""Titanic_Survival.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zEkt0gSZEEPwgpARmZz1HK7JaQIIGujv
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv(r'/content/sample_data/Titanic-Dataset.csv')
df = pd.DataFrame(data)
print(df.head())

df.Age.describe()

df.Age.median()

df.Age.mode()

missing_age_rows = df[df['Age'].isnull()]
print(missing_age_rows[['Name', 'Age']])

df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
title_medians = df.groupby('Title')['Age'].median()

def fill_age(row):
    if pd.isnull(row['Age']):
        return title_medians[row['Title']]
    else:
        return row['Age']

df['Age'] = df.apply(fill_age, axis=1)

print(df['Age'].isnull().sum())
print(df['Title'].isnull().sum())

print(df[['Name', 'Age']].loc[65])

plt.scatter(x = df["Age"] , y = df["Fare"])

df['Embarked'] = df['Embarked'].fillna(df.Embarked.mode()[0])
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

df['Embarked'] = df['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})
df['HasCabin'] = df['Cabin'].notnull().astype(int)

df.drop(columns=['PassengerId'],inplace=True)
df.drop(columns=['Ticket'],inplace=True)
df.drop(columns=['Cabin'],inplace=True)
df.drop(columns=['Name'],inplace=True)
df.drop(columns=['Title'],inplace=True)

df['SocioEconomicStatus'] = df['Pclass'] * (1 / (df['Fare'] + 1))
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
# df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

df.drop(columns=['SibSp'],inplace=True)
df.drop(columns=['Parch'],inplace=True)
# df.drop(columns=['Pclass'],inplace=True)
# df.drop(columns=['Fare'],inplace=True)

df.info()

numeric_df = df.select_dtypes(include=['float64', 'int64'])
correlation_matrix = numeric_df.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

survival_counts = df['Survived'].value_counts()
print(survival_counts)

numerical_features = ['Age', 'Fare', 'FamilySize']
categorical_features = ['Pclass', 'Sex', 'Embarked', 'HasCabin', 'SocioEconomicStatus']

df = pd.get_dummies(df, columns=categorical_features, drop_first=True)

X = df.drop('Survived', axis=1)
y = df['Survived']

scaler = StandardScaler()
X[numerical_features] = scaler.fit_transform(X[numerical_features])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
