# -*- coding: utf-8 -*-
"""Movie_Rating.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G37ebtx07nHDmPNjAgC6jqjhszaeBUY2
"""

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MultiLabelBinarizer, OneHotEncoder, StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv(r'/content/sample_data/IMDb_Movies_India.csv', encoding='latin-1')
df=pd.DataFrame(data)
print(df)

missing_percentage = (data.isnull().sum() / len(data)) * 100
print(missing_percentage)

df = df.drop(columns=['Duration'])

def clean_year(year):
    if pd.isna(year):  # Check for NaN values
        return np.nan
    elif isinstance(year, str) and year.isdigit():
        return int(year)
    elif isinstance(year, str):
        y = year.strip('()')
        return int(y)
    elif isinstance(year, (int, float)):
        return int(year)
    return None
df['Year'] = df['Year'].apply(clean_year)
df['Year'] = df.groupby('Director')['Year'].transform(
    lambda group: group.fillna(group.median())
)
df['Year'] = df['Year'].fillna(df['Year'].median())
df['Year'] = df['Year'].astype(int)

df['Year'] = df['Year'].astype(float)
movies_per_year = df['Year'].value_counts().sort_index()
colors = ['purple', 'pink', 'brown', 'Turquoise', 'yellow', 'lightblue', 'salmon', 'skyblue', 'teal', 'orange', 'lightgreen', 'Crimson']
random.shuffle(colors)
plt.figure(figsize=(12, 6))
plt.bar(movies_per_year.index, movies_per_year.values, color=colors)
plt.xlabel('Year')
plt.ylabel('Number of Movies Released')
plt.title('Number of Movies Released Each Year')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

all_genres = df['Genre'].dropna().str.split(', ').explode().unique()
print(sorted(all_genres))

director_genre_mode = (
    df.groupby('Director')['Genre']
    .apply(lambda x: Counter(x.dropna()).most_common(1)[0][0] if not x.dropna().empty else None)
    .to_dict()
)

actor1_genre_mode = (
    df.groupby('Actor 1')['Genre']
    .apply(lambda x: Counter(x.dropna()).most_common(1)[0][0] if not x.dropna().empty else None)
    .to_dict()
)

def fill_genre(row):
    if pd.notna(row['Genre']):
        return row['Genre']
    if pd.notna(row['Director']) and row['Director'] in director_genre_mode:
        return director_genre_mode[row['Director']]
    if pd.notna(row['Actor 1']) and row['Actor 1'] in actor1_genre_mode:
        return actor1_genre_mode[row['Actor 1']]
    return None

df['Genre'] = df.apply(fill_genre, axis=1)
df = df.drop(columns=['Actor 3'])
print(df.head())

df['Genre'] = df['Genre'].fillna('Unknown')
genre_counts = df['Genre'].str.split(', ').explode().value_counts()

plt.figure(figsize=(14, 7))
bars = genre_counts.plot(kind='bar', color='mediumpurple', edgecolor='black', alpha=0.85)
plt.title('Frequency of Movies by Genre', fontsize=18, fontweight='bold', color='darkblue', pad=20)
plt.xlabel('Genre', fontsize=14, fontweight='bold', color='darkred', labelpad=10)
plt.ylabel('Number of Movies', fontsize=14, fontweight='bold', color='darkred', labelpad=10)
plt.xticks(rotation=45, ha='right', fontsize=12, color='navy')
plt.yticks(fontsize=12, color='navy')
plt.grid(axis='y', linestyle='--', alpha=0.6)

for bar in bars.patches:
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        int(bar.get_height()),
        ha='center',
        va='bottom',
        fontsize=10,
        color='black'
    )
plt.tight_layout()
plt.show()

df = df.dropna(subset=['Rating', 'Votes','Director'], how='all')
median_rating_by_director = df.groupby('Director')['Rating'].transform('median')
df['Rating'] = df['Rating'].fillna(median_rating_by_director)
median_rating_by_actor1 = df.groupby('Actor 1')['Rating'].transform('median')
df['Rating'] = df['Rating'].fillna(median_rating_by_actor1)
df = df.dropna(subset=['Rating'], how='all')
df['Votes'] = pd.to_numeric(df['Votes'].str.replace(', ', '', regex=True), errors='coerce')
median_votes_by_director = df.groupby('Director')['Votes'].transform('median')
median_votes_by_actor1 = df.groupby('Actor 1')['Votes'].transform('median')
df['Votes'] = df['Votes'].fillna(median_votes_by_director)
df['Votes'] = df['Votes'].fillna(median_votes_by_actor1)
df['Votes'] = df['Votes'].fillna(df['Votes'].median())
print(repr(df.head(10)))

for col in ['Rating', 'Votes']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df = df.dropna(subset=['Director'], how='all')
df['Actor 1'] = df['Actor 1'].fillna('Unknown')
df['Actor 2'] = df['Actor 2'].fillna('Unknown')

numeric_columns = df.select_dtypes(include=['float64', 'int64'])
correlation_matrix = numeric_columns.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

df.info()

df['Genre'] = df['Genre'].str.split(', ')
mlb = MultiLabelBinarizer()
genre_encoded = pd.DataFrame(mlb.fit_transform(df['Genre']), columns=mlb.classes_)

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
director_actor_encoded = pd.DataFrame(
    encoder.fit_transform(df[['Director', 'Actor 1']]),
    columns=encoder.get_feature_names_out()
)

scaler = StandardScaler()
scaled_features = pd.DataFrame(
    scaler.fit_transform(df[['Year', 'Votes']]),
    columns=['Year', 'Votes']
)

X = pd.concat([scaled_features, genre_encoded, director_actor_encoded], axis=1)

y = df['Rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)
print(f"Root Mean Squared Error: {rmse}")
print(f"R² (Coefficient of Determination): {r2}")

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='green', alpha=0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--k', lw=2)
plt.xlabel('Actual Ratings')
plt.ylabel('Predicted Ratings')
plt.title('Actual vs. Predicted Ratings')
plt.show()

result_df = pd.DataFrame({'Actual Ratings': y_test, 'Predicted Ratings': y_pred})

plt.figure(figsize=(8, 4))
sns.barplot(data=result_df, palette='pastel')

plt.xlabel('Sample Index')
plt.ylabel('Movie Ratings')
plt.title('Comparison of Actual vs Predicted Movie Ratings')
plt.legend(loc='upper right')
plt.show()